name: Deploy Mapbox Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace Mapbox Token in HTML
        env:
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
        run: |

          sed -i 's/YOUR_MAPBOX_ACCESS_TOKEN/'"$MAPBOX_ACCESS_TOKEN"'/' sketch.html

      - name: Deploy or Serve
        run: |

          echo "Deploying..."
